"""third revision

Revision ID: 0631fe16769a
Revises: 483c17c9b724
Create Date: 2022-09-29 12:26:14.837636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0631fe16769a'
down_revision = '483c17c9b724'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
