"""second revision

Revision ID: 27601ffb1e9c
Revises: 700a6ea03bae
Create Date: 2022-09-29 10:11:55.382298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27601ffb1e9c'
down_revision = '700a6ea03bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('std_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'faculty', 'student', ['std_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculty', type_='foreignkey')
    op.drop_column('faculty', 'std_id')
    # ### end Alembic commands ###
