"""third revision

Revision ID: 35ed37db0016
Revises: 0631fe16769a
Create Date: 2022-09-29 15:59:52.886351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ed37db0016'
down_revision = '0631fe16769a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_F_id_fkey', 'student', type_='foreignkey')
    op.drop_column('student', 'F_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('F_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('student_F_id_fkey', 'student', 'faculty', ['F_id'], ['id'])
    # ### end Alembic commands ###
