"""second revision

Revision ID: 483c17c9b724
Revises: ae053189da69
Create Date: 2022-09-29 12:04:18.680132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '483c17c9b724'
down_revision = 'ae053189da69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty', 'f_subject')
    op.drop_constraint('student_F_id_fkey', 'student', type_='foreignkey')
    op.create_foreign_key(None, 'student', 'faculty', ['F_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.create_foreign_key('student_F_id_fkey', 'student', 'student', ['F_id'], ['id'])
    op.add_column('faculty', sa.Column('f_subject', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
