"""changes

Revision ID: 686ac63fe139
Revises: 9c8e6f39746d
Create Date: 2022-10-04 16:26:54.971116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '686ac63fe139'
down_revision = '9c8e6f39746d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_F_id_fkey', 'student', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('student_F_id_fkey', 'student', 'faculty', ['F_id'], ['id'])
    # ### end Alembic commands ###
