"""first revision

Revision ID: 700a6ea03bae
Revises: 
Create Date: 2022-09-28 16:15:43.554738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '700a6ea03bae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('faculty_std_id_fkey', 'faculty', type_='foreignkey')
    op.drop_column('faculty', 'std_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty', sa.Column('std_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('faculty_std_id_fkey', 'faculty', 'student', ['std_id'], ['id'])
    # ### end Alembic commands ###
