"""third revision

Revision ID: 9c8e6f39746d
Revises: 35ed37db0016
Create Date: 2022-09-29 16:52:50.677951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8e6f39746d'
down_revision = '35ed37db0016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('F_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student', 'faculty', ['F_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'F_id')
    # ### end Alembic commands ###
