"""second revision

Revision ID: ae053189da69
Revises: 9cbfb42a000f
Create Date: 2022-09-29 11:44:25.142562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae053189da69'
down_revision = '9cbfb42a000f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
